---

   - name: add main domain
     lineinfile:
       path: /etc/sssd/sssd.conf
       regexp: '^(.*)domains = {{ sub_domain }}'
       line: 'domains = {{ sub_domain }}, {{ domain }}'
       state: present

   - name: pam offline credential expiration
     lineinfile:
       path: /etc/sssd/sssd.conf
       line: 'offline_credentials_expiration = 3'
       insertafter: '^\[pam\]'

   - name: sssd offline credential expiration    
     lineinfile:
      path: /etc/sssd/sssd.conf
      line: 'offline_credentials_expiration = 3 '
      insertafter: '^\[sssd\]'

   - name: sssd cache credentials
     lineinfile:
       path: /etc/sssd/sssd.conf
       line: 'cache_credentials = true'
       insertafter: '^\[sssd\]'

   - name: sssd cache expiration
     lineinfile:
       path: /etc/sssd/sssd.conf
       line: 'account_cache_expiration = 7'
       insertafter: '^\[sssd\]'

   - name: sssd timeout
     lineinfile:
       path: /etc/sssd/sssd.conf
       line: 'entry_cache_timeout = 14400'
       insertafter: '^\[sssd\]'

   - name: sudo domains
     lineinfile:
       path: /etc/sssd/sssd.conf
       line: 'domains = {{ sub_domain }},{{ domain }}'
       insertafter: '^\[sudo\]'
