---

  - name: ipa client install variable include
    include_vars: "../vars/vars.yml"

  - name: install ipa client
    shell: "ipa-client-install --domain={{ sub_domain }} \
    --realm={{ realm }} \
    -p {{ principal }} -w {{ password }} \
    --force-join --ntp-server={{ ntp }} -f -d -U \
    --mkhomedir"

    
